In [39]:
import numpy as np
import pandas as pd

Creating a DataFrame

In [40]:
data = {
    'Name':['John','Anna','Petter','Linda'],
    'Age':[28,34,29,42],
    'City': ['New York','Paris','Berlin','London'],
    'Salary':[65000,70000,62000,85000]
}
df = pd.DataFrame(data)
df

     Name  Age      City  Salary
0    John   28  New York   65000
1    Anna   34     Paris   70000
2  Petter   29    Berlin   62000
3   Linda   42    London   85000

In [41]:
data_list = [
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Pette',29,'Paris',62000],
    ['Linda',42,'London',85000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns=columns)

In [42]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Pette   29     Paris   62000
3  Linda   42    London   85000

Selection and Indexing Of Columns

In [43]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Pette   29     Paris   62000
3  Linda   42    London   85000

In [44]:
df2['Name']

0     John
1     Anna
2    Pette
3    Linda
Name: Name, dtype: object

In [45]:
df2['City']

0    New York
1       Paris
2       Paris
3      London
Name: City, dtype: object

In [46]:
df2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Pette     Paris
3  Linda    London

Creating a new column

In [47]:
df2["Designation"] = ["Doctor","Engineer","Doctor","Engineer"]

In [48]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Pette   29     Paris   62000      Doctor
3  Linda   42    London   85000    Engineer

Removing a column

In [49]:
df2.drop('Designation',axis = 1 ,inplace = True)

In [50]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Pette   29     Paris   62000
3  Linda   42    London   85000

In [52]:
df2.drop(['City','Name'],axis = 1 ,inplace = True)

In [53]:
df2

   Age  Salary
0   28   65000
1   34   70000
2   29   62000
3   42   85000

In [55]:
df2.drop(0,axis = 0 )

   Age  Salary
1   34   70000
2   29   62000
3   42   85000

Selecting Rows

In [59]:
df2.loc[0]

Age          28
Salary    65000
Name: 0, dtype: int64

In [62]:
df2.loc[[0,1]]

   Age  Salary
0   28   65000
1   34   70000

In [63]:
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

Selecting Subset of Rows and Columns

In [68]:
df.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [69]:
df.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [73]:
df.loc[[2,3]][['Name','Age']]

     Name  Age
2  Petter   29
3   Linda   42

Conditional Selection

In [75]:
data_list = [
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Pette',29,'Paris',62000],
    ['Linda',42,'London',85000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Pette   29     Paris   62000
3  Linda   42    London   85000

In [76]:
#age>30
df2[df2['Age']>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [78]:
#age>30 & belongs to paris
df2[(df2['Age']>30) & (df2['City']=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000