In [2]:
import numpy as np
import pandas as pd

Merging 2 dataframes

In [5]:
employees = pd.DataFrame({
    'employee_id' :[1,2,3,4,5],
    'name':['john','anna','peter','linda','bob'],
    'department' :['teacher','IT','finance','IT','HR']
})
#DATAFRAME SALARY INFO
salaries = pd.DataFrame({
    'employee_id' :[1,2,3,6,7],
    'salary':[60000,80000,65000,70000,90000],
    'bonus' :[5000,10000,7000,8000,12000]
})

In [6]:
employees

   employee_id   name department
0            1   john    teacher
1            2   anna         IT
2            3  peter    finance
3            4  linda         IT
4            5    bob         HR

In [7]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [12]:
pd.merge(employees,salaries, on = 'employee_id',how = 'inner')

   employee_id   name department  salary  bonus
0            1   john    teacher   60000   5000
1            2   anna         IT   80000  10000
2            3  peter    finance   65000   7000

In [13]:
pd.merge(employees,salaries, on = 'employee_id',how = 'outer')

   employee_id   name department   salary    bonus
0            1   john    teacher  60000.0   5000.0
1            2   anna         IT  80000.0  10000.0
2            3  peter    finance  65000.0   7000.0
3            4  linda         IT      NaN      NaN
4            5    bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [14]:
pd.merge(employees,salaries, on = 'employee_id',how = 'left')

   employee_id   name department   salary    bonus
0            1   john    teacher  60000.0   5000.0
1            2   anna         IT  80000.0  10000.0
2            3  peter    finance  65000.0   7000.0
3            4  linda         IT      NaN      NaN
4            5    bob         HR      NaN      NaN

In [15]:
pd.merge(employees,salaries, on = 'employee_id',how = 'right')

   employee_id   name department  salary  bonus
0            1   john    teacher   60000   5000
1            2   anna         IT   80000  10000
2            3  peter    finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [ ]:
Joining 2 dataframes

In [23]:
df1 = pd.DataFrame({
    'name':['Alice','Bob','Charlie']
},index = [1,2,3])

df2 = pd.DataFrame({
    'score':[85,90,75]
},index = [2,3,4])

In [24]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [25]:
df2

   score
2     85
3     90
4     75

In [26]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [27]:
df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

Concatenation 2 dataframes

In [16]:
df1 = pd.DataFrame({
    'A':['AB','A1','A2'],
    'B':['BC','B1','B2'],
    'C':['C0','C1','C2']
})
df2 = pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','C5'],
    'C':['C3','C4','C5']
})

In [17]:
df1

    A   B   C
0  AB  BC  C0
1  A1  B1  C1
2  A2  B2  C2

In [18]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  C5  C5

In [21]:
pd.concat([df1,df2])

    A   B   C
0  AB  BC  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  C5  C5

In [22]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  AB  BC  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  C5  C5